language: node_js

env:
  global:
    - secure: aF1dlCEpQnaNJyvMCHP5QJBBIvV3wef1Kewuwi1M4G/6IBxKDEhbq4OQrQ3ai0BCedyXiWdVmvggYBZc0cwDgGZQPJlYsWhdoxxracAfVvPSkMHz17Q6TESRsR7AB+QE2b1qC03Y1euIR1kymdbkKBdEkYtT3O94pnI2gHGE0Tt+HCltUdJ+PeV/djiz6GJxhY75axKBxzrUJVtTXHuM6rmVLcz6S817R3ZfddQ/5VeuEk3zTDEITExw6NoKxid1bD/sdxqi8A0QAsnbLTaBj62awoauA9xlN9JgeWmcbSj/b9JZjaOAxmrs2nEAoGZ/XmRnAzGxTar42EkixjbVEOuCzQBkI1ZAG/zBriCgm+Ou7OPyoMwq4UvGNJyCha7kMTWQ57DnfkZcFDqPw0CZ0XlGuTDVF7bZGmpZPauBOF12/nOGWqnrSBXPT0pUhA/iKUB6my7DmMYU6m/+13Lcg0XInD5cWRacBP/Wtzct1SShU4DWTE0lavSrVlt6e87VoVse0cL+rmHVIgcEgBXHDt3Q+jrf5nls/dK5JBdynoW++iFgmVH+2lz7WTY755ETd1Ed99HV/lfqRgSo6jIsG19riTFOEqB2cHClddbCpAI06QDRgv7NObzQGUYa9K4SfR1657Wd5eMmlnFMu+EFkKCrjcnyn+DHKMzUPTRzUCE=
    - secure: JmeSQ3AGCqhUVLkRz0jgZyxHyfINtdpYAbnKwDCeB9whYZ2KOeli8jO1fiqX0duaVhTicrTA2IfyuLnBuhT8MHiEOcoiNXdvs3NPGIA4hjB+chJ3Eg6rfGAoWk+wQE62qWjRF38v8/YDLqoRVjShdaBdHHwY/XC2fh7M52E1qv1ojl3xyxwNTGcHQ7LiWa8dIgO7r5tqZFKXa94AKXSDiokav03IyAqpE/ZHUcyTOQSg4DpPhmBhNkgDqjinKVIBKRFkD6GchmEt+PdGFfT4xuMBnbTjbghzSe6tGGYN1aWYe6X7fhwyvKcJbUBfFOTPDPe6NJPv/6YwcRDZ4o1kpVJowPSB67rFr7K7KPO6mNyhITQlwCpAxwAsCneRHkxBeV8b4aySifgtJW0clrPsG3jnZNmhGfk90lZkRlpI/ZgXK2a8UdJ2JafU8gzZfJlxALQOK5kkDV1FaWyLbuKAM8TVm1m2vIGe54pv/flYCjZQPQ1cCrmL0WDEbVPZD0EP8JCntD40ivCOlO1/V6ri36EgVcex9ucr624EMOSMfU98VT0RQ55ZTRAHJp5b/ag5IrmIRSV4qmgdOzqr88VmdeDJ7P1JEpvM06xYK3MPomqLOL4b1CztjFA8CupAwCnIaTA+oydCNqIVE+gvhBYTO3ICMl9UQC5k11n79xGfBGU=

node_js:
  - 8.9

before_script:
  - nightwatch --version
  - java -version
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - make test

dist: trusty

sudo: required

addons:
  chrome: stable
