var path = require('path');
var fs = require('fs');

module.exports = {
  'init empty': function(browser) {
    browser
      .url('file://' + path.join(__dirname, 'index.html'))
      .waitForElementVisible('body', 1000)
      .assert.containsText('#test li[title="1个变量"]', '')
      .assert.containsText('#test li[title="静态+变量"]', 'before')
      .assert.containsText('#test li[title="变量+静态"]', 'after')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforeafter')
      .assert.containsText('#test li[title="变量+变量"]', '')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'middle')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforemiddleafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'DOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOM')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMDOM')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'DOM')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'DOMDOM')
      .assert.containsText('#test p[ref="1"]', '1,1,1,1,1,1,1,2,2,3,4,3,4,')
      .assert.containsText('#test p[ref="2"]', ',before,after,beforeafter,,middle,beforemiddleafter,<span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span>,<span migi-uid="15">DOM</span><span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span><span migi-uid="19">DOM</span>,<span migi-uid="21">DOM</span>,<span migi-uid="23">DOM</span><span migi-uid="24">DOM</span>,')
  },
  'empty2[d,d]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'dd')
      .assert.containsText('#test li[title="静态+变量"]', 'beforedd')
      .assert.containsText('#test li[title="变量+静态"]', 'ddafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforeddafter')
      .assert.containsText('#test li[title="变量+变量"]', 'dddd')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'ddmiddledd')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforeddmiddleddafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'ddDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMdd')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMddDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMddDOMdd')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'ddDOMdd')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'ddDOMddDOM')
      .assert.containsText('#test div p[ref="1"]', '2,3,3,4,4,5,7,3,3,4,6,5,6,')
      .assert.containsText('#test div p[ref="2"]', '<b migi-uid="28">d</b><b migi-uid="29">d</b>,before<b migi-uid="28">d</b><b migi-uid="29">d</b>,<b migi-uid="28">d</b><b migi-uid="29">d</b>after,before<b migi-uid="28">d</b><b migi-uid="29">d</b>after,<b migi-uid="28">d</b><b migi-uid="29">d</b><b migi-uid="28">d</b><b migi-uid="29">d</b>,<b migi-uid="28">d</b><b migi-uid="29">d</b>middle<b migi-uid="28">d</b><b migi-uid="29">d</b>,before<b migi-uid="28">d</b><b migi-uid="29">d</b>middle<b migi-uid="28">d</b><b migi-uid="29">d</b>after,<b migi-uid="28">d</b><b migi-uid="29">d</b><span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span><b migi-uid="28">d</b><b migi-uid="29">d</b>,<span migi-uid="15">DOM</span><b migi-uid="28">d</b><b migi-uid="29">d</b><span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span><b migi-uid="28">d</b><b migi-uid="29">d</b><span migi-uid="19">DOM</span><b migi-uid="28">d</b><b migi-uid="29">d</b>,<b migi-uid="28">d</b><b migi-uid="29">d</b><span migi-uid="21">DOM</span><b migi-uid="28">d</b><b migi-uid="29">d</b>,<b migi-uid="28">d</b><b migi-uid="29">d</b><span migi-uid="23">DOM</span><b migi-uid="28">d</b><b migi-uid="29">d</b><span migi-uid="24">DOM</span>,')
  },
  '[d,d]2[t,t]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'tt')
      .assert.containsText('#test li[title="静态+变量"]', 'beforett')
      .assert.containsText('#test li[title="变量+静态"]', 'ttafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforettafter')
      .assert.containsText('#test li[title="变量+变量"]', 'tttt')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'ttmiddlet')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforettmiddlettafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'ttDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMtt')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMttDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMttDOMtt')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'ttDOMtt')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'ttDOMttDOM')
      .assert.containsText('#test div p[ref="1"]', '1,1,1,1,1,1,1,2,2,3,4,3,4,')
      .assert.containsText('#test div p[ref="2"]', 'tt,beforett,ttafter,beforettafter,tttt,ttmiddlett,beforettmiddlettafter,tt<span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span>tt,<span migi-uid="15">DOM</span>tt<span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span>tt<span migi-uid="19">DOM</span>tt,tt<span migi-uid="21">DOM</span>tt,tt<span migi-uid="23">DOM</span>tt<span migi-uid="24">DOM</span>,')
  },
  '[t,t]2[d,d,t]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'ddt')
      .assert.containsText('#test li[title="静态+变量"]', 'beforeddt')
      .assert.containsText('#test li[title="变量+静态"]', 'ddtafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforeddtafter')
      .assert.containsText('#test li[title="变量+变量"]', 'ddtddt')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'ddtmiddleddt')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforeddtmiddleddtafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'ddtDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMddt')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMddtDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMddtDOMddt')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'ddtDOMddt')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'ddtDOMddtDOM')
      .assert.containsText('#test div p[ref="1"]', '3,4,3,4,6,6,7,4,4,5,8,7,8,')
      .assert.containsText('#test div p[ref="2"]', '<b migi-uid="30">d</b><b migi-uid="31">d</b>t,before<b migi-uid="30">d</b><b migi-uid="31">d</b>t,<b migi-uid="30">d</b><b migi-uid="31">d</b>tafter,before<b migi-uid="30">d</b><b migi-uid="31">d</b>tafter,<b migi-uid="30">d</b><b migi-uid="31">d</b>t<b migi-uid="30">d</b><b migi-uid="31">d</b>t,<b migi-uid="30">d</b><b migi-uid="31">d</b>tmiddle<b migi-uid="30">d</b><b migi-uid="31">d</b>t,before<b migi-uid="30">d</b><b migi-uid="31">d</b>tmiddle<b migi-uid="30">d</b><b migi-uid="31">d</b>tafter,<b migi-uid="30">d</b><b migi-uid="31">d</b>t<span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span><b migi-uid="30">d</b><b migi-uid="31">d</b>t,<span migi-uid="15">DOM</span><b migi-uid="30">d</b><b migi-uid="31">d</b>t<span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span><b migi-uid="30">d</b><b migi-uid="31">d</b>t<span migi-uid="19">DOM</span><b migi-uid="30">d</b><b migi-uid="31">d</b>t,<b migi-uid="30">d</b><b migi-uid="31">d</b>t<span migi-uid="21">DOM</span><b migi-uid="30">d</b><b migi-uid="31">d</b>t,<b migi-uid="30">d</b><b migi-uid="31">d</b>t<span migi-uid="23">DOM</span><b migi-uid="30">d</b><b migi-uid="31">d</b>t<span migi-uid="24">DOM</span>,')
  },
  '[d,d,t]2[t,t]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'tt')
      .assert.containsText('#test li[title="静态+变量"]', 'beforett')
      .assert.containsText('#test li[title="变量+静态"]', 'ttafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforettafter')
      .assert.containsText('#test li[title="变量+变量"]', 'tttt')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'ttmiddlett')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforettmiddlettafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'ttDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMtt')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMttDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMttDOMtt')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'ttDOMtt')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'ttDOMttDOM')
      .assert.containsText('#test div p[ref="1"]', '1,1,1,1,1,1,1,2,2,3,4,3,4,')
      .assert.containsText('#test div p[ref="2"]', 'tt,beforett,ttafter,beforettafter,tttt,ttmiddlett,beforettmiddlettafter,tt<span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span>tt,<span migi-uid="15">DOM</span>tt<span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span>tt<span migi-uid="19">DOM</span>tt,tt<span migi-uid="21">DOM</span>tt,tt<span migi-uid="23">DOM</span>tt<span migi-uid="24">DOM</span>,')
  },
  '[t,t]2[d,t,t]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'dtt')
      .assert.containsText('#test li[title="静态+变量"]', 'beforedtt')
      .assert.containsText('#test li[title="变量+静态"]', 'dttafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforedttafter')
      .assert.containsText('#test li[title="变量+变量"]', 'dttdtt')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'dttmiddledtt')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforedttmiddledttafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'dttDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMdtt')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMdttDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMdttDOMdtt')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'dttDOMdtt')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'dttDOMdttDOM')
      .assert.containsText('#test div p[ref="1"]', '2,3,2,3,4,4,5,3,3,4,6,5,6,')
      .assert.containsText('#test div p[ref="2"]', '<b migi-uid="32">d</b>tt,before<b migi-uid="32">d</b>tt,<b migi-uid="32">d</b>ttafter,before<b migi-uid="32">d</b>ttafter,<b migi-uid="32">d</b>tt<b migi-uid="32">d</b>tt,<b migi-uid="32">d</b>ttmiddle<b migi-uid="32">d</b>tt,before<b migi-uid="32">d</b>ttmiddle<b migi-uid="32">d</b>ttafter,<b migi-uid="32">d</b>tt<span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span><b migi-uid="32">d</b>tt,<span migi-uid="15">DOM</span><b migi-uid="32">d</b>tt<span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span><b migi-uid="32">d</b>tt<span migi-uid="19">DOM</span><b migi-uid="32">d</b>tt,<b migi-uid="32">d</b>tt<span migi-uid="21">DOM</span><b migi-uid="32">d</b>tt,<b migi-uid="32">d</b>tt<span migi-uid="23">DOM</span><b migi-uid="32">d</b>tt<span migi-uid="24">DOM</span>,')
  },
  '[d,t,t]2[d,d,d]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'ddd')
      .assert.containsText('#test li[title="静态+变量"]', 'beforeddd')
      .assert.containsText('#test li[title="变量+静态"]', 'dddafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforedddafter')
      .assert.containsText('#test li[title="变量+变量"]', 'dddddd')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'dddmiddleddd')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforedddmiddledddafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'dddDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMddd')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMdddDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMdddDOMddd')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'dddDOMddd')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'dddDOMdddDOM')
      .assert.containsText('#test div p[ref="1"]', '3,4,4,5,6,7,9,4,4,5,8,7,8,')
      .assert.containsText('#test div p[ref="2"]', '<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>,before<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>,<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>after,before<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>after,<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b><b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>,<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>middle<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>,before<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>middle<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>after,<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b><span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span><b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>,<span migi-uid="15">DOM</span><b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b><span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span><b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b><span migi-uid="19">DOM</span><b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>,<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b><span migi-uid="21">DOM</span><b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b>,<b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b><span migi-uid="23">DOM</span><b migi-uid="32">d</b><b migi-uid="34">d</b><b migi-uid="35">d</b><span migi-uid="24">DOM</span>,')
  },
  '[d,d,d]2[t,t,d]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'ttd')
      .assert.containsText('#test li[title="静态+变量"]', 'beforettd')
      .assert.containsText('#test li[title="变量+静态"]', 'ttdafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforettdafter')
      .assert.containsText('#test li[title="变量+变量"]', 'ttdttd')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'ttdmiddlettd')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforettdmiddlettdafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'ttdDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMttd')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMttdDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMttdDOMttd')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'ttdDOMttd')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'ttdDOMttdDOM')
      .assert.containsText('#test div p[ref="1"]', '2,2,3,3,4,4,5,3,3,4,6,5,6,')
      .assert.containsText('#test div p[ref="2"]', 'tt<b migi-uid="35">d</b>,beforett<b migi-uid="35">d</b>,tt<b migi-uid="35">d</b>after,beforett<b migi-uid="35">d</b>after,tt<b migi-uid="35">d</b>tt<b migi-uid="35">d</b>,tt<b migi-uid="35">d</b>middlett<b migi-uid="35">d</b>,beforett<b migi-uid="35">d</b>middlett<b migi-uid="35">d</b>after,tt<b migi-uid="35">d</b><span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span>tt<b migi-uid="35">d</b>,<span migi-uid="15">DOM</span>tt<b migi-uid="35">d</b><span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span>tt<b migi-uid="35">d</b><span migi-uid="19">DOM</span>tt<b migi-uid="35">d</b>,tt<b migi-uid="35">d</b><span migi-uid="21">DOM</span>tt<b migi-uid="35">d</b>,tt<b migi-uid="35">d</b><span migi-uid="23">DOM</span>tt<b migi-uid="35">d</b><span migi-uid="24">DOM</span>,')
  },
  '[t,t,d]2[d,d,d]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'ddd')
      .assert.containsText('#test li[title="静态+变量"]', 'beforeddd')
      .assert.containsText('#test li[title="变量+静态"]', 'dddafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforedddafter')
      .assert.containsText('#test li[title="变量+变量"]', 'dddddd')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'dddmiddleddd')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforedddmiddledddafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'dddDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMddd')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMdddDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMdddDOMddd')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'dddDOMddd')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'dddDOMdddDOM')
      .assert.containsText('#test div p[ref="1"]', '3,4,4,5,6,7,9,4,4,5,8,7,8,')
      .assert.containsText('#test div p[ref="2"]', '<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>,before<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>,<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>after,before<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>after,<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b><b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>,<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>middle<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>,before<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>middle<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>after,<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b><span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span><b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>,<span migi-uid="15">DOM</span><b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b><span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span><b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b><span migi-uid="19">DOM</span><b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>,<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b><span migi-uid="21">DOM</span><b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b>,<b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b><span migi-uid="23">DOM</span><b migi-uid="37">d</b><b migi-uid="38">d</b><b migi-uid="35">d</b><span migi-uid="24">DOM</span>,')
  },
  '[d,d,d]2[d,t,t]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'dtt')
      .assert.containsText('#test li[title="静态+变量"]', 'beforedtt')
      .assert.containsText('#test li[title="变量+静态"]', 'dttafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforedttafter')
      .assert.containsText('#test li[title="变量+变量"]', 'dttdtt')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'dttmiddledtt')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforedttmiddledttafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'dttDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMdtt')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMdttDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMdttDOMdtt')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'dttDOMdtt')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'dttDOMdttDOM')
      .assert.containsText('#test div p[ref="1"]', '2,3,2,3,4,4,5,3,3,4,6,5,6,')
      .assert.containsText('#test div p[ref="2"]', '<b migi-uid="37">d</b>tt,before<b migi-uid="37">d</b>tt,<b migi-uid="37">d</b>ttafter,before<b migi-uid="37">d</b>ttafter,<b migi-uid="37">d</b>tt<b migi-uid="37">d</b>tt,<b migi-uid="37">d</b>ttmiddle<b migi-uid="37">d</b>tt,before<b migi-uid="37">d</b>ttmiddle<b migi-uid="37">d</b>ttafter,<b migi-uid="37">d</b>tt<span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span><b migi-uid="37">d</b>tt,<span migi-uid="15">DOM</span><b migi-uid="37">d</b>tt<span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span><b migi-uid="37">d</b>tt<span migi-uid="19">DOM</span><b migi-uid="37">d</b>tt,<b migi-uid="37">d</b>tt<span migi-uid="21">DOM</span><b migi-uid="37">d</b>tt,<b migi-uid="37">d</b>tt<span migi-uid="23">DOM</span><b migi-uid="37">d</b>tt<span migi-uid="24">DOM</span>,')
  },
  '[d,t,t]2[t,t,t]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'ttt')
      .assert.containsText('#test li[title="静态+变量"]', 'beforettt')
      .assert.containsText('#test li[title="变量+静态"]', 'tttafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforetttafter')
      .assert.containsText('#test li[title="变量+变量"]', 'tttttt')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'tttmiddlettt')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforetttmiddletttafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'tttDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMttt')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMtttDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMtttDOMttt')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'tttDOMttt')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'tttDOMtttDOM')
      .assert.containsText('#test div p[ref="1"]', '1,1,1,1,1,1,1,2,2,3,4,3,4,')
      .assert.containsText('#test div p[ref="2"]', 'ttt,beforettt,tttafter,beforetttafter,tttttt,tttmiddlettt,beforetttmiddletttafter,ttt<span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span>ttt,<span migi-uid="15">DOM</span>ttt<span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span>ttt<span migi-uid="19">DOM</span>ttt,ttt<span migi-uid="21">DOM</span>ttt,ttt<span migi-uid="23">DOM</span>ttt<span migi-uid="24">DOM</span>,')
  },
  '[t,t,t]2[d,d,d]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'ddd')
      .assert.containsText('#test li[title="静态+变量"]', 'beforeddd')
      .assert.containsText('#test li[title="变量+静态"]', 'dddafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforedddafter')
      .assert.containsText('#test li[title="变量+变量"]', 'dddddd')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'dddmiddleddd')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforedddmiddledddafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'dddDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMddd')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMdddDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMdddDOMddd')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'dddDOMddd')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'dddDOMdddDOM')
      .assert.containsText('#test div p[ref="1"]', '3,4,4,5,6,7,9,4,4,5,8,7,8,')
      .assert.containsText('#test div p[ref="2"]', '<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>,before<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>,<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>after,before<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>after,<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b><b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>,<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>middle<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>,before<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>middle<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>after,<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b><span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span><b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>,<span migi-uid="15">DOM</span><b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b><span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span><b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b><span migi-uid="19">DOM</span><b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>,<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b><span migi-uid="21">DOM</span><b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b>,<b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b><span migi-uid="23">DOM</span><b migi-uid="41">d</b><b migi-uid="42">d</b><b migi-uid="43">d</b><span migi-uid="24">DOM</span>,')
  },
  '[d,d,d]2[t,t,t]': function(browser) {
    browser
      .click('#test strong')
      .assert.containsText('#test li[title="1个变量"]', 'ttt')
      .assert.containsText('#test li[title="静态+变量"]', 'beforettt')
      .assert.containsText('#test li[title="变量+静态"]', 'tttafter')
      .assert.containsText('#test li[title="静态+变量+静态"]', 'beforetttafter')
      .assert.containsText('#test li[title="变量+变量"]', 'tttttt')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'tttmiddlettt')
      .assert.containsText('#test li[title="静态+变量+静态+变量+静态"]', 'beforetttmiddletttafter')
      .assert.containsText('#test li[title="变量+DOM"]', 'tttDOM')
      .assert.containsText('#test li[title="DOM+变量"]', 'DOMttt')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'DOMtttDOM')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'DOMtttDOMttt')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'tttDOMttt')
      .assert.containsText('#test li[title="变量+DOM+变量+DOM"]', 'tttDOMtttDOM')
      .assert.containsText('#test div p[ref="1"]', '1,1,1,1,1,1,1,2,2,3,4,3,4,')
      .assert.containsText('#test div p[ref="2"]', 'ttt,beforettt,tttafter,beforetttafter,tttttt,tttmiddlettt,beforetttmiddletttafter,ttt<span migi-uid="11">DOM</span>,<span migi-uid="13">DOM</span>ttt,<span migi-uid="15">DOM</span>ttt<span migi-uid="16">DOM</span>,<span migi-uid="18">DOM</span>ttt<span migi-uid="19">DOM</span>ttt,ttt<span migi-uid="21">DOM</span>ttt,ttt<span migi-uid="23">DOM</span>ttt<span migi-uid="24">DOM</span>,')
      .end()
  }
};