var path = require('path');
var fs = require('fs');

module.exports = {
  'init empty': function(browser) {
    browser
      .url('file://' + path.join(__dirname, 'index.html'))
      .waitForElementVisible('body', 1000)
      .assert.containsText('#test li[title="1个文本变量"]', '')
      .assert.containsText('#test li[title="2个文本变量"]', '')
      .assert.containsText('#test li[title="静态+变量"]', 'start')
      .assert.containsText('#test li[title="变量+静态"]', 'end')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'middle')
      .assert.containsText('#test li[title="空+变量"]', '')
      .assert.containsText('#test li[title="变量+空"]', '')
      .assert.containsText('#test li[title="变量+空+变量"]', '')
      .assert.containsText('#test li[title="DOM+变量"]', 'dom')
      .assert.containsText('#test li[title="变量+DOM"]', 'dom')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'domdom')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'domdom')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'dom')
      .assert.containsText('#test li[title="变量+[]+变量"]', '')
      .assert.containsText('#test li[title="变量+undefined+变量"]', '')
      .assert.containsText('#test li[title="变量+null+变量"]', '')
      .assert.containsText('#test strong', '1,1,1,1,1,1,1,1,2,2,3,4,3,1,1,1,')
  },
  'add': function(browser) {
    browser
      .click('#test p[ref="add"]')
      .assert.containsText('#test li[title="1个文本变量"]', '01')
      .assert.containsText('#test li[title="2个文本变量"]', '0101')
      .assert.containsText('#test li[title="静态+变量"]', 'start 01')
      .assert.containsText('#test li[title="变量+静态"]', '01 end')
      .assert.containsText('#test li[title="变量+静态+变量"]', '01 middle 01')
      .assert.containsText('#test li[title="空+变量"]', '01')
      .assert.containsText('#test li[title="变量+空"]', '01')
      .assert.containsText('#test li[title="变量+空+变量"]', '0101')
      .assert.containsText('#test li[title="DOM+变量"]', 'dom01')
      .assert.containsText('#test li[title="变量+DOM"]', '01dom')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'dom01dom')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'dom01dom01')
      .assert.containsText('#test li[title="变量+DOM+变量"]', '01dom01')
      .assert.containsText('#test li[title="变量+[]+变量"]', '0101')
      .assert.containsText('#test li[title="变量+undefined+变量"]', '0101')
      .assert.containsText('#test li[title="变量+null+变量"]', '0101')
      .assert.containsText('#test strong', '1,1,1,1,1,1,1,1,2,2,3,4,3,1,1,1,')
  },
  'add again': function(browser) {
    browser
      .click('#test p[ref="add"]')
      .assert.containsText('#test li[title="1个文本变量"]', '0123')
      .assert.containsText('#test li[title="2个文本变量"]', '01230123')
      .assert.containsText('#test li[title="静态+变量"]', 'start 0123')
      .assert.containsText('#test li[title="变量+静态"]', '0123 end')
      .assert.containsText('#test li[title="变量+静态+变量"]', '0123 middle 0123')
      .assert.containsText('#test li[title="空+变量"]', '0123')
      .assert.containsText('#test li[title="变量+空"]', '0123')
      .assert.containsText('#test li[title="变量+空+变量"]', '01230123')
      .assert.containsText('#test li[title="DOM+变量"]', 'dom0123')
      .assert.containsText('#test li[title="变量+DOM"]', '0123dom')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'dom0123dom')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'dom0123dom0123')
      .assert.containsText('#test li[title="变量+DOM+变量"]', '0123dom0123')
      .assert.containsText('#test li[title="变量+[]+变量"]', '01230123')
      .assert.containsText('#test li[title="变量+undefined+变量"]', '01230123')
      .assert.containsText('#test li[title="变量+null+变量"]', '01230123')
      .assert.containsText('#test strong', '1,1,1,1,1,1,1,1,2,2,3,4,3,1,1,1,')
  },
  'del': function(browser) {
    browser
      .click('#test p[ref="del"]')
      .assert.containsText('#test li[title="1个文本变量"]', '01')
      .assert.containsText('#test li[title="2个文本变量"]', '0101')
      .assert.containsText('#test li[title="静态+变量"]', 'start 01')
      .assert.containsText('#test li[title="变量+静态"]', '01 end')
      .assert.containsText('#test li[title="变量+静态+变量"]', '01 middle 01')
      .assert.containsText('#test li[title="空+变量"]', '01')
      .assert.containsText('#test li[title="变量+空"]', '01')
      .assert.containsText('#test li[title="变量+空+变量"]', '0101')
      .assert.containsText('#test li[title="DOM+变量"]', 'dom01')
      .assert.containsText('#test li[title="变量+DOM"]', '01dom')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'dom01dom')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'dom01dom01')
      .assert.containsText('#test li[title="变量+DOM+变量"]', '01dom01')
      .assert.containsText('#test li[title="变量+[]+变量"]', '0101')
      .assert.containsText('#test li[title="变量+undefined+变量"]', '0101')
      .assert.containsText('#test li[title="变量+null+变量"]', '0101')
      .assert.containsText('#test strong', '1,1,1,1,1,1,1,1,2,2,3,4,3,1,1,1,')
  },
  'del again': function(browser) {
    browser
      .click('#test p[ref="del"]')
      .assert.containsText('#test li[title="1个文本变量"]', '')
      .assert.containsText('#test li[title="2个文本变量"]', '')
      .assert.containsText('#test li[title="静态+变量"]', 'start')
      .assert.containsText('#test li[title="变量+静态"]', 'end')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'middle')
      .assert.containsText('#test li[title="空+变量"]', '')
      .assert.containsText('#test li[title="变量+空"]', '')
      .assert.containsText('#test li[title="变量+空+变量"]', '')
      .assert.containsText('#test li[title="DOM+变量"]', 'dom')
      .assert.containsText('#test li[title="变量+DOM"]', 'dom')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'domdom')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'domdom')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'dom')
      .assert.containsText('#test li[title="变量+[]+变量"]', '')
      .assert.containsText('#test li[title="变量+undefined+变量"]', '')
      .assert.containsText('#test li[title="变量+null+变量"]', '')
      .assert.containsText('#test strong', '1,1,1,1,1,1,1,1,2,2,3,4,3,1,1,1,')
  },
  'empty del': function(browser) {
    browser
      .click('#test p[ref="del"]')
      .assert.containsText('#test li[title="1个文本变量"]', '')
      .assert.containsText('#test li[title="2个文本变量"]', '')
      .assert.containsText('#test li[title="静态+变量"]', 'start')
      .assert.containsText('#test li[title="变量+静态"]', 'end')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'middle')
      .assert.containsText('#test li[title="空+变量"]', '')
      .assert.containsText('#test li[title="变量+空"]', '')
      .assert.containsText('#test li[title="变量+空+变量"]', '')
      .assert.containsText('#test li[title="DOM+变量"]', 'dom')
      .assert.containsText('#test li[title="变量+DOM"]', 'dom')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'domdom')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'domdom')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'dom')
      .assert.containsText('#test li[title="变量+[]+变量"]', '')
      .assert.containsText('#test li[title="变量+undefined+变量"]', '')
      .assert.containsText('#test li[title="变量+null+变量"]', '')
      .assert.containsText('#test strong', '1,1,1,1,1,1,1,1,2,2,3,4,3,1,1,1,')
  },
  'add 2': function(browser) {
    browser
      .click('#test p[ref="add"]')
      .assert.containsText('#test li[title="1个文本变量"]', '45')
      .assert.containsText('#test li[title="2个文本变量"]', '4545')
      .assert.containsText('#test li[title="静态+变量"]', 'start 45')
      .assert.containsText('#test li[title="变量+静态"]', '45 end')
      .assert.containsText('#test li[title="变量+静态+变量"]', '45 middle 45')
      .assert.containsText('#test li[title="空+变量"]', '45')
      .assert.containsText('#test li[title="变量+空"]', '45')
      .assert.containsText('#test li[title="变量+空+变量"]', '4545')
      .assert.containsText('#test li[title="DOM+变量"]', 'dom45')
      .assert.containsText('#test li[title="变量+DOM"]', '45dom')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'dom45dom')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'dom45dom45')
      .assert.containsText('#test li[title="变量+DOM+变量"]', '45dom45')
      .assert.containsText('#test li[title="变量+[]+变量"]', '4545')
      .assert.containsText('#test li[title="变量+undefined+变量"]', '4545')
      .assert.containsText('#test li[title="变量+null+变量"]', '4545')
      .assert.containsText('#test strong', '1,1,1,1,1,1,1,1,2,2,3,4,3,1,1,1,')
  },
  'del 2': function(browser) {
    browser
      .click('#test p[ref="del"]')
      .assert.containsText('#test li[title="1个文本变量"]', '')
      .assert.containsText('#test li[title="2个文本变量"]', '')
      .assert.containsText('#test li[title="静态+变量"]', 'start')
      .assert.containsText('#test li[title="变量+静态"]', 'end')
      .assert.containsText('#test li[title="变量+静态+变量"]', 'middle')
      .assert.containsText('#test li[title="空+变量"]', '')
      .assert.containsText('#test li[title="变量+空"]', '')
      .assert.containsText('#test li[title="变量+空+变量"]', '')
      .assert.containsText('#test li[title="DOM+变量"]', 'dom')
      .assert.containsText('#test li[title="变量+DOM"]', 'dom')
      .assert.containsText('#test li[title="DOM+变量+DOM"]', 'domdom')
      .assert.containsText('#test li[title="DOM+变量+DOM+变量"]', 'domdom')
      .assert.containsText('#test li[title="变量+DOM+变量"]', 'dom')
      .assert.containsText('#test li[title="变量+[]+变量"]', '')
      .assert.containsText('#test li[title="变量+undefined+变量"]', '')
      .assert.containsText('#test li[title="变量+null+变量"]', '')
      .assert.containsText('#test strong', '1,1,1,1,1,1,1,1,2,2,3,4,3,1,1,1,')
      .end()
  }
};